[[JeeTS-Web-Spring-Traccar]]

:toc:

= The JeeTS Web Software

The Name JeeTS reflects "GPS Tracking Software with Java EE", 
i.e. "Jee" T.S. like in G.T.S. +
JeeTS components are developed against the Traccar GTS as de facto standard
and can be combined with it in many, also complimentary, ways
to create individual Tracking Solutions and integrate them into existing Systems.

The JeeTS Source Code is hosted in the two Repositories
// absolute paths to github server, use internal relative paths!
// define base path before /jeets and /jeets-web

 * https://github.com/kbeigl/jeets/[*/jeets*] +
  Tracking Components compatible with the Traccar Backend customizable
   for individual Tracking Solutions

 * https://github.com/kbeigl/jeets-web/[*/jeets-web*] +
  In its core a Spring MVC Component to rapidly develop individual Frontends 
  with different Spring-Boot Starters against the Traccar REST API



=== Release Notes

Major improvements and development states are listed in the 

 * link:./jeets-web-docs/ReleaseNotes.adoc[JeeTS Web Release Notes]


== Building the JeeTS Repositories

Please check the link:https://github.com/kbeigl/jeets/[*/jeets*] 
project for build instructions. +

Instructions to compile and test each repository.
Please note that the two repositories are build independent of each other.
Their structures are updated and synchronized continuously 
and the installation process is the same for each repository.
The link above is describing how to compile the JeeTS repository
but also applies to the JeeTS Web repository.
Generally the regular JeeTS repository should be compiled first
to supply artifacts for the JeeTS Web build.


=== Developing JeeTS with Eclipse

Please check the link:https://github.com/kbeigl/jeets/[*/jeets*] 
project for instructions to import the repository 
or individual projects in Eclipse. +

The instructions also apply for the JeeTS Web repository.


=== Issue Tracking

In case of problems please report your issues here: 
link:https://github.com/kbeigl/jeets-web/issues[JeeTS Web issues]


== JeeTS Web Inline Documentation

On the link:./jeets-web-docs/jeets-toc.adoc[JeeTS Web table of content] page 
you will find links to this repositories inline documentation to get started.


== Contact

Please login to github to find the email in my link:https://github.com/kbeigl[profile]


== License

    Apache License, Version 2.0
    .
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    . 
    .   http://www.apache.org/licenses/LICENSE-2.0
    .
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
