[[web-vaadin]]

:toc:


= JeeTS Web Vaadin

This project provides a starter to create your own Traccar Frontend - rapidly.
It implies the `jeets-web-spring-traccar` project 
which controls the embedded Tomcat Servlet Engine
and has a built in *Open API Client for Traccar*.


== Install Node.js

We expect you to be familiar with JeeTS and have followed the instructions
to install a Java Developer Kit, the Maven Build Tool, Git Version Control,
that you have run a `mvn clean install` over this repository
and maybe have already imported the projects into your IDE.
This process works for the regular _JeeTS_ repository.

In case of the _JeeTS Web_ you will run into a build problem without the 
link:https://nodejs.org[Front-end build tool Node.js],
a JavaScript run-time environment - _installed on your OS!_
Vaadin uses Node internally to build an optimized version of your app.

Node Installation steps:

 * Go to the link:https://nodejs.org/en/download/[Node.js download page]

 * Download and run the Installer for your system +
   (different operating systems are covered in the Vaadin Tutorial pdf)
 
 * Follow the prompts in the wizard.
 
 * It is highly recommended to install the 'live reload' in your browser
   as described in the same document. + 
   This provides the perfect development environment 
   reflecting every change immediately in your browser.

Now the `mvn install` process should run smoothly, 
you should see the `npm install` in the logs
and the repository should compile with `BUILD SUCCESS`.


== Run Out of the Box

This `jeets-web-vaadin` project provides a functional frontend application 
to be installed on any server. In addition you can also run it 
in your local environment with for development and for Traccar Management.


=== Install

First you need to run

    mvn clean install 
    
over the complete repository. Note that the install process creates
a new folder in the Vaadin project

    ...\jeets-web-vaadin\node_modules
    
and when you run Vaadin the first time with
    
    ...\jeets-web-vaadin\mvn spring-boot:run

the new folder should be filled and is logged with

    16:19:12.008  INFO 16012 --- [restartedMain] dev-updater:
          Running `npm install` to resolve and optionally download frontend dependencies. 
          This may take a moment, please stand by...
    16:23:17.372  INFO 16012 --- [restartedMain] dev-updater: 
          Frontend dependencies resolved successfully.

This first run loads the vaadin resources (javaskript elements etc.) to your repo
and the `node_modules` folder should be filled with about 18.000 files with a total size of 88 MB. In this case an average machine took about four minutes. 
After the folder is filled the process should start Tomcat and after you see this line 

    Started webpack-dev-server. Time: 17039ms
    
you can open the application in the browser

    http://localhost:8080

You are ready to implement your own administration to analyze and clean data 
and many other things to support your customers.
    

==== ServletException and ServiceException

Please note that `mvn spring-boot:run` occasionally runs into timing
problems and you will see Exceptions on command line _and_ in the browser:

    javax.servlet.ServletException: com.vaadin.flow.server.ServiceException: 
      com.vaadin.flow.server.BootstrapException: Unable to read webpack stats file.
      com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:249)
         :

In this case you should simply rerun the command line and 
it should automatically display the login screen.


=== Traccar Server Instance

You should keep in mind that this project is simply an alternative frontend
to the provided `traccar-web` project. 
Both rely on a running Traccar backend server with a REST API.

If you have your own Traccar Server running 
you can configure it in the `application.yml` file
of the underlying `jeets-web-spring-traccar` project!

    rest:
       protocol: https://
       server: traccar.virtex.de
       api: /api

This server config is composed in the `TraccarAuthenticationProvider`

    @Value("${rest.protocol}${rest.server}${rest.api}")
    private String restServerApi; //         => "https://traccar.virtex.de/api"

If you _do not_ have your own Traccar Server running you can also use
one of link:https://www.traccar.org/demo-server/[Traccar's Demo Servers]

    rest:
       protocol: http://
       server: demo3.traccar.org
       api: /api

In this case you will need a valid user to login via Vaadin.
To get one you simply register a new user on the demo server.
Then you can login to create a device dedicated to the user 
and finally you can install the Traccar Client on your smartphone
to get some tracking data to work with.

IMPORTANT: The disadvantage of using a demo server is that you can only
register a regular user and therefore cannot develop 
for Traccar Managers and Administrators.


== Explore Vaadin

After you have gone through the setup once you can start learning and developing. +
The simple link:architecture.adoc[architecture of the project is described here]  +
where you will also find links to related Vaadin Tutorials. 





